packaging_format = 2

id = "haste"
name = "Haste"
description.en = "Open-source pastebin allowing to upload texts"
description.fr = "Pastebin open-source permettant de mettre en ligne du texte"

version = "0.1.2024.06.17~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://www.toptal.com/developers/hastebin"
userdoc = "https://www.toptal.com/developers/hastebin/about"
code = "https://github.com/toptal/haste-server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Haste will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Haste sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/toptal/haste-server/archive/87a6a88449db1e1e048bf58223038b8df83846c8.tar.gz"
        sha256 = "729cdff777daa04ccc277670a94e2e8e5d7bf4cd1bf63730d3436bca5d05dd6d"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.force_version = "0.1.%Y.%m.%d"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
