packaging_format = 2

id = "haste"
name = "Haste"
description.en = "Open-source pastebin allowing to upload texts"
description.fr = "Pastebin open-source permettant de mettre en ligne du texte"

version = "0.1.0~ynh3"

maintainers = []

[upstream]
license = "MIT"
website = "http://hastebin.com/"
demo = "http://hastebin.com/"
userdoc = "https://hastebin.com/about.md"
code = "https://github.com/toptal/haste-server"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Haste will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Haste sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/YunoHost-Apps/haste_ynh/archive/refs/tags/0.1.0.tar.gz"
        sha256 = "e95dde1457ee310bc3a197f7ddfe9dd217ef255df6be4625adcdc959958e6291"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
