#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Installing dependencies..."

# Install Nodejs
ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir=$install_dir

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

env_path="$PATH"
ynh_config_add_systemd

mkdir -p /var/log/$app
touch /var/log/$app/$app.log

ynh_config_add_logrotate

yunohost service add $app --description="Haste is a pastebin software" --log="/var/log/$app/$app.log"

#=================================================
# CONFIGURE HASTE
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.js" --destination="$install_dir/config.js"

# Replace ajax.googleapis by local file
cp ../sources/jquery.min.js "$install_dir/static/jquery.min.js"

ynh_replace --match="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" --replace="jquery.min.js" --file="$install_dir/static/index.html"

#=================================================
# INSTALL HASTEBIN
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	ynh_hide_warnings npm install
popd

#=================================================
# ADD HASTE AS A BINARY FILE
#=================================================

haste_url="${domain}${path}"
ynh_config_add --template="haste.sh" --destination="/usr/bin/$app"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chmod +x /usr/bin/$app

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
