#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

if yunohost service status | grep -q $app
then
	echo "Remove $app service"
	yunohost service remove $app
fi

#=================================================
# REMOVE APP MAIN DIR
#=================================================

ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# FIXME Currently, the log is only redirected to syslog.
# ynh_remove_logrotate

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE HASTE BINARY
#=================================================

ynh_secure_remove "/usr/bin/$app"

#=================================================
# REMOVE DATADIR DIRECTORY
#=================================================

ynh_secure_remove "/home/yunohost.app/$app"

#=================================================
# REMOVE NODEJS
#=================================================

ynh_remove_nodejs

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

# Delete a system user
ynh_system_user_delete $app
