#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Reinstalling dependencies..."

ynh_nodejs_install

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R $app:www-data "$data_dir"

#=================================================
# RESTORE BINARY
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/usr/bin/$app"
chmod +x /usr/bin/$app

#=================================================
# RESTORE HANDLE LOG FILES
#=================================================

mkdir -p /var/log/$app
touch /var/log/$app/$app.log
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app -R /var/log/$app

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="Haste is a pastebin software" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
