#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --keep="config.js"

#=================================================
# UPGRADE NODEJS
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_nodejs_install

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# FIXME Currently, the log is only redirected to syslog.
ynh_config_add_logrotate

env_path="$PATH"
ynh_config_add_systemd

yunohost service add $app --description="Haste is a pastebin software" --log="/var/log/$app/$app.log"

#=================================================
# UPGRADE NPM MODULES
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"

	ynh_hide_warnings npm install
popd

#=================================================
# UPGRADE HASTE CONFIGURATION
#=================================================

# Replace ajax.googleapis by local file
cp ../sources/jquery.min.js "$install_dir/static/jquery.min.js"

ynh_replace --match="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" --replace="jquery.min.js" --file="$install_dir/static/index.html"

#=================================================
# UPGRADE HASTE BINARY
#=================================================
ynh_script_progression "Updating configuration..."

haste_url="${domain}${path}"
ynh_config_add --template="haste.sh" --destination="/usr/bin/$app"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
chmod +x /usr/bin/$app

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
